services:
  postgres:
    image: postgres:15-alpine
    container_name: hums_postgres
    environment:
      POSTGRES_USER: user_hums
      POSTGRES_PASSWORD: password_hums
      POSTGRES_DB: hums_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: